### ISSUE TITLE
Re-enable codesigning for Windows build

### ISSUE THREAD

**Issue by ribose-jeffreylau** [paneron/paneron#87]
[Here are the instructions to using KeyLocker with electron-builder in GitHub Actions.](https://docs.digicert.com/en/digicert-keylocker/ci-cd-integrations/plugins/github-custom-action-for-keypair-signing.html#ksp-signing-using-github-action-488715)

Prerequisites:

- [ ] #88

## Tasks

- [x] set `secrets.SM_HOST`, the path to the DigiCert ONE portal with client authorization (for US: `https://clientauth.one.digicert.com`)
- [ ] set `secrets.SM_API_KEY`, the API token generated during API token setup
- [ ] set `secrets.SM_CLIENT_CERT_PASSWORD`, the password from client authentication certificate setup
- [ ] set `secrets.SM_CLIENT_CERT_FILE_B64`, the base64 encoded text of certificate downloaded from client authentication certificate setup
- [ ] set `secrets.SM_CODE_SIGNING_CERT_SHA1_HASH`, the certificate fingerprint
